CREATE TABLE PRODUCTS (
	PARTNUMBER INT NOT NULL PRIMARY KEY,
	DESCRIPTION VARCHAR(60) ,
	PRICE DOUBLE PRECISION NOT NULL,
	SUPPLIERNAME VARCHAR(30) ,
	COST DOUBLE PRECISION
);
INSERT INTO PRODUCTS (PARTNUMBER, DESCRIPTION, PRICE, SUPPLIERNAME, COST)
	VALUES (1001, 'Carpet Cleaner', 1.65, 'KleenKo', 0.62);
INSERT INTO PRODUCTS (PARTNUMBER, DESCRIPTION, PRICE, SUPPLIERNAME, COST)
	VALUES (2001, 'A Space Odyssey', 15.99, 'Kubrick', 5.50);

CREATE TABLE SALESPEOPLE (
	NAME VARCHAR(20) PRIMARY KEY NOT NULL, 
	SALESTARGET DOUBLE PRECISION NOT NULL, 
	CREATED DATE,
	SALES DOUBLE PRECISION NOT NULL, 
	PHOTOFILE VARCHAR(40));
INSERT INTO SALESPEOPLE (NAME, SALESTARGET, SALES, PHOTOFILE)
	VALUES ('John', 4000, 150, 'john.gif');
INSERT INTO SALESPEOPLE (NAME, SALESTARGET, SALES, PHOTOFILE)
	VALUES ('Julie', 2000, 2140, 'julie.gif');

CREATE TABLE ENGSPA (
	ENGLISH VARCHAR(30) NOT NULL PRIMARY KEY,
	SPANISH VARCHAR(30) NOT NULL,
	WORD_TYPE CHAR(1),
	SUB_TYPE CHAR(1),
	CATEGORY VARCHAR(20)
);
INSERT INTO ENGSPA VALUES ('apple','manzana','n','f','food');
INSERT INTO ENGSPA VALUES ('pear','pera','n','f','food');
INSERT INTO ENGSPA VALUES ('orange','naranja','n','f','food');
INSERT INTO ENGSPA VALUES ('strawberry','fresa','n','f','food');
INSERT INTO ENGSPA VALUES ('grapefruit','pomelo','n','m','food');
INSERT INTO ENGSPA VALUES ('grape','uva','n','f','food');
INSERT INTO ENGSPA VALUES ('raspberry','frambuesa','n','f','food');
INSERT INTO ENGSPA VALUES ('beer','cerveza','n','f','drink');
INSERT INTO ENGSPA VALUES ('water','agua','n','m','drink');
INSERT INTO ENGSPA VALUES ('wine','vino','n','m','drink');

SELECT * FROM ENGSPA;